INSERT INTO AEROPORTO(ID,NAME) VALUES (1,'POA');
INSERT INTO AEROPORTO(ID,NAME) VALUES (2,'FLO');
INSERT INTO AEROPORTO(ID,NAME) VALUES (3,'SP');

INSERT INTO ROTAS(ID,NAME) VALUES (1,'Rota1');
INSERT INTO ROTAS(ID,NAME) VALUES (2,'Rota2');
INSERT INTO ROTAS(ID,NAME) VALUES (3,'Rota3');

INSERT INTO LINHAS_AEREAS (ID,NAME,airRoute,from,to) VALUES (1,'Linha1', 'Rota1' ,'POA','FLO');
INSERT INTO LINHAS_AEREAS (ID,NAME,airRoute,from,to) VALUES (2,'Linha2', 'Rota1'  ,'POA','SP');
INSERT INTO LINHAS_AEREAS (ID,NAME,airRoute,from,to) VALUES (3,'Linha3', 'Rota2'  ,'SP','FLO');
INSERT INTO LINHAS_AEREAS (ID,NAME,airRoute,from,to) VALUES (4,'Linha3', 'Rota2'  ,'FLO','POA');
INSERT INTO LINHAS_AEREAS (ID,NAME,airRoute,from,to) VALUES (5,'Linha3', 'Rota3'  ,'FLO','SP');
INSERT INTO LINHAS_AEREAS (ID,NAME,airRoute,from,to) VALUES (6,'Linha3', 'Rota3'  ,'SP','POA');
