INSERT INTO AEROPORTO(ID,NAME) VALUES (1,'POA');
INSERT INTO AEROPORTO(ID,NAME) VALUES (2,'FLO');
INSERT INTO AEROPORTO(ID,NAME) VALUES (3,'SP');

INSERT INTO ROTAS(ID,NAME) VALUES (1,'Rota1');
INSERT INTO ROTAS(ID,NAME) VALUES (2,'Rota2');
INSERT INTO ROTAS(ID,NAME) VALUES (3,'Rota3');

INSERT INTO LINHAS_AEREAS(ID,NAME) VALUES (1,'Linha1');
INSERT INTO LINHAS_AEREAS(ID,NAME) VALUES (2,'Linha2');
INSERT INTO LINHAS_AEREAS(ID,NAME) VALUES (3,'Linha3');

INSERT INTO PLANO_VOO (ID,ALTITUDE,CRUISING_SPEED,DATE,DISPATCHED,FLIGHT_NUMBER ) VALUES (2,4000,550.0,'2023-02-02',0,1);


INSERT INTO AVIOES(ID,AUTONOMY,CRUISING_SPEED,PREFIX ) VALUES (1,1000,850.0,'PPCST');
INSERT INTO AVIOES(ID,AUTONOMY,CRUISING_SPEED,PREFIX ) VALUES (2,2000,550.0,'PRBST');
INSERT INTO AVIOES(ID,AUTONOMY,CRUISING_SPEED,PREFIX ) VALUES (3,3000,650.0,'PSCST');
INSERT INTO AVIOES(ID,AUTONOMY,CRUISING_SPEED,PREFIX ) VALUES (4,4000,550,'PTDST');
